const products=[
[1,"Xiaomi Redmi Note 14 Pro+ 5G","Tecnología","20260517_210451.jpg","Smartphone nuevo en caja · 5G · consulta capacidad y especificaciones","Destacado","$229.990"],
[2,"Azzaro Forever Wanted","Perfumes","20260721_003352.jpg","Perfume masculino Azzaro · producto en caja","","$55.000"],
[3,"Azzaro Wanted","Perfumes",["20260721_003421.jpg","20260721_003444.jpg"],"Perfume masculino Azzaro Wanted · producto en caja","2 unidades","$45.000"],
[4,"Azzaro The Most Wanted","Perfumes","20260721_003433.jpg","Perfume masculino Azzaro · producto en caja","","$45.000"],
[5,"Azzaro Wanted Eau de Parfum","Perfumes","20260721_003553.jpg","Perfume masculino Azzaro Wanted · presentación individual","","$60.000"],
[6,"Set Azzaro Wanted","Perfumes",["20260721_003605.jpg","20260721_003613.jpg"],"Estuche con perfume, miniatura y producto de cuidado personal","Set regalo","$60.000"],
[7,"Set Hugo Boss The Scent","Perfumes",["20260721_003726.jpg","20260721_003730.jpg"],"Estuche con perfume, miniatura y producto de cuidado personal","Set regalo","$60.000"],
[8,"Sofá gris de tres cuerpos","Hogar",["20260724_125700.jpg","20260724_125723.jpg","20260724_125735.jpg","20260724_125739.jpg","20260724_125743.jpg","20260724_125745.jpg"],"Sofá amplio color gris, NO reclinable · coordinar retiro","Retiro","$90.000"],
[9,"Lote de perfumes Azzaro","Perfumes","20260726_130139.jpg","Conjunto de cuatro perfumes Azzaro en caja","Lote","$45.000"],
[10,"Auto Mercedes rojo a batería","Otros","669366377_904313255941917_7588542433340182220_n.jpg","Auto infantil rojo estilo Mercedes · consultar características","","$80.000"],
[11,"Cafetera Nespresso Vertuo Pop","Hogar","Gemini_Generated_Image_wh2jb2wh2jb2wh2j.jpg","Cafetera Nespresso Vertuo Pop con cápsulas y accesorios","Oferta","$60.000"],
[12,"Zapatillas Adidas","Calzado","WhatsApp Image 2026-04-27 at 10.18.42.jpg","Zapatillas Adidas nuevas en caja · consultar modelo y talla","Varias unidades","$30.000"]
];
const categories=["Todos","Perfumes","Tecnología","Hogar","Calzado","Otros"];let active="Todos",query="";
const grid=document.querySelector("#product-grid"),count=document.querySelector("#result-count"),empty=document.querySelector("#empty"),filters=document.querySelector("#filters");
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function drawFilters(){filters.innerHTML=categories.map(c=>`<button class="${c===active?"active":""}" data-category="${c}">${c}</button>`).join("");filters.querySelectorAll("button").forEach(b=>b.onclick=()=>{active=b.dataset.category;drawFilters();render()})}
function render(){const q=query.trim().toLocaleLowerCase("es"),list=products.filter(p=>(active==="Todos"||p[2]===active)&&(!q||`${p[0]} ${p[1]} ${p[2]} ${p[4]}`.toLocaleLowerCase("es").includes(q)));count.innerHTML=`Catálogo actualizado. <strong>${list.length} ${list.length===1?"artículo":"artículos"}</strong>.`;grid.hidden=!list.length;empty.hidden=!!list.length;grid.innerHTML=list.map((p,i)=>{const imgs=Array.isArray(p[3])?p[3]:[p[3]],text=encodeURIComponent(`Hola, me interesa el artículo #${p[0]}: ${p[1]}, publicado a ${p[6]}. ¿Sigue disponible?`);return `<article class="card" style="--delay:${Math.min(i,11)*35}ms"><div class="card-image gallery" data-slide="0">${imgs.map((img,n)=>`<img src="${encodeURI(img)}" alt="${escapeHtml(p[1])}${imgs.length>1?` · foto ${n+1}`:""}" loading="lazy" class="${n===0?"active":""}">`).join("")}<span class="item-number">Item #${p[0]}</span>${p[5]?`<span class="badge">${escapeHtml(p[5])}</span>`:""}${imgs.length>1?`<button class="gallery-prev" aria-label="Foto anterior">‹</button><button class="gallery-next" aria-label="Foto siguiente">›</button><span class="gallery-count">1/${imgs.length}</span>`:""}</div><div class="card-body"><p class="category">${p[2]}</p><h3>${escapeHtml(p[1])}</h3><p class="details">${escapeHtml(p[4])}</p><div class="card-footer"><span class="price">${escapeHtml(p[6]||"Consultar precio")}</span><a class="buy-btn" href="https://wa.me/56932494457?text=${text}" target="_blank" rel="noreferrer">Comprar</a></div></div></article>`}).join("");activateGalleries()}
function activateGalleries(){grid.querySelectorAll(".gallery").forEach(g=>{const imgs=[...g.querySelectorAll("img")],label=g.querySelector(".gallery-count");if(imgs.length<2)return;const move=d=>{let n=(+g.dataset.slide+d+imgs.length)%imgs.length;g.dataset.slide=n;imgs.forEach((im,i)=>im.classList.toggle("active",i===n));label.textContent=`${n+1}/${imgs.length}`};g.querySelector(".gallery-prev").onclick=e=>{e.preventDefault();move(-1)};g.querySelector(".gallery-next").onclick=e=>{e.preventDefault();move(1)}})}
document.querySelector("#search").addEventListener("input",e=>{query=e.target.value;render()});drawFilters();render();
